function [centcoord]=peakfinder(vqnan)
    % To be called by function 'topo'. Returns weighted peak centroid 
    % coordinates from variable 'vqnan' generated by 'topo'. This is a 
    % moving threshold, which reduces if fewer than three peaks are found 
    % (up to two steps of 10% of the original threshold value). 

    %If <2 peaks identified after two threshold steps, uses fastpeakfind.m
    %to try to acquire peaks.
    
    vqnan1=vqnan;

    %peakfinder struggles with low elevation peaks associated with Al-(100)
    q=sum(vqnan1(:,1:end),2);
    v=cumtrapz(q);

    if prctile(v,20)/max(v) > 0.2 % Selection Rule: If more than a fifth of the data is below 20 degrees elevation - i.e. flat surface 
        centcoord=lowpeaks(vqnan1);
    else

    % Normalize input data to range in [0,1].
    Xmin = min(vqnan1(:));
    Xmax = max(vqnan1(:));
    if isequal(Xmax,Xmin)
        vqnan1 = 0*vqnan1;
    else
        vqnan1 = (vqnan1 - Xmin) ./ (Xmax - Xmin);
    end
    % First pass
    T = graythresh(vqnan1);     % Find threshold for binarization ('otsu')
    BW1 = imbinarize(vqnan1);   % Perform binarization to generate mask
    BW1=Imageproc(BW1);         % Tidy up mask
    BW2=BW1.*vqnan1;            % Multiply the mask by the original image
    sproperties = regionprops(BW1,BW2,{'WeightedCentroid'});
    centcoord = cat(1,sproperties.WeightedCentroid);

    if (centcoord(1,1)<30 && centcoord(end,1)>330)  %where a peak is split over the Az origin
            centcoord=splitpeaks(centcoord);
    end
    if length(centcoord)<3 % Second pass
        T1=T*0.9; % Reduce threshold by 10% 
        BW1 = vqnan1 > T1;
        BW1=Imageproc(BW1);
        BW2=BW1.*vqnan1;
        sproperties = regionprops(BW1,BW2,{'WeightedCentroid'});
        centcoord = cat(1,sproperties.WeightedCentroid);
        
        if (centcoord(1,1)<30 && centcoord(end,1)>330)  
                centcoord=splitpeaks(centcoord);
        end
    end
    if length(centcoord)<3 % Third pass
        T2=T*0.8; %Reduce threshold by 20%
        BW1 = vqnan1 > T2;
        BW1=Imageproc(BW1);
        BW2=BW1.*vqnan1;
        sproperties = regionprops(BW1,BW2,{'WeightedCentroid'});
        centcoord = cat(1,sproperties.WeightedCentroid);
        
        if (centcoord(1,1)<30 && centcoord(end,1)>330)  
                centcoord=splitpeaks(centcoord);
        end
    end
    if min(size(centcoord))<2 % Final pass if only one peak is identified
        cent=FastPeakFind(vqnan1);
        centcoord = zeros(length(cent)/2,2);    %New variable for x,y positions in 2-column xy format
        centcoord(:,1) = cent(1:2:end);         %Odd indices (x position Az)
        centcoord(:,2) = cent(2:2:end);         %Even indices (y position El)
        
        if length(centcoord)<1
            centcoord=[0 0];
        end 
        if  (centcoord(1,1)<30 && centcoord(end,1)>330)  
                centcoord=splitpeaks(centcoord);
        end
    end   
    end
end